### ISSUE TITLE
Inconsitent use of validator identifiers between the Keymanager API and the Beacon API

### ISSUE THREAD

**Issue by zah** [ethereum/keymanager-APIs#36]
In the URLs of the standard Beacon API, validators can be identified through both their public keys and their numeric identifiers. The documentation of the Keymanager API suggests that only a public key will be recognized in the `feerecipient` calls.

**Comment by michaelsproul** [comment]
I think we could probably support indices too, but pubkeys are the default because they're more flexible (they allow configuring keys that aren't active yet). There's also implementation complexity around what to do if the VC hasn't loaded the validator index for a key yet: do you error?

On the whole I'm weakly against adding any validator-index APIs to the VC, for simplicity

**Comment by ajsutton** [comment]
We can't support validator indices in the key manager api. Apart from the case of the validator index not yet existing because the deposit hasn't been made, external signers have no way of mapping from validator index to public key.

**Comment by ajsutton** [comment]
That said, the fee recipient calls won't be implemented by external signers at all because they don't deal with fee recipient, but I think it would be very confusing to have some APIs that support indices and some that don't (and no way in this API to lookup a validator index).

**Comment by zah** [comment]
OK, I think this issue can be closed then.
